package com.ubb.fmi.orar.domain.analytics.model

/**
 * Events for logging key actions in Firebase
 */
enum class AnalyticsEvent(val id: String) {
    CONFIG_STUDENT("CONFIG_STUDENT"),
    CONFIG_TEACHER("CONFIG_TEACHER"),

    VIEW_TIMETABLE_GROUP("VIEW_TIMETABLE_GROUP"),
    VIEW_TIMETABLE_TEACHER("VIEW_TIMETABLE_TEACHER"),
    VIEW_TIMETABLE_SUBJECT("VIEW_TIMETABLE_SUBJECT"),
    VIEW_TIMETABLE_ROOM("VIEW_TIMETABLE_ROOM"),

    NEWS_ACCESS_STUDENT("NEWS_ACCESS_STUDENT"),
    NEWS_ACCESS_TEACHER("NEWS_ACCESS_TEACHER"),

    ADD_PERSONAL_EVENT("ADD_PERSONAL_EVENT"),

    ADOPT_EVENT("ADOPT_EVENT"),

    FREE_ROOM_SEARCH("FREE_ROOM_SEARCH"),

    FEEDBACK_SHOW("FEEDBACK_SHOW"),
    FEEDBACK_NEGATIVE("FEEDBACK_NEGATIVE"),
    FEEDBACK_NEUTRAL("FEEDBACK_NEUTRAL"),
    FEEDBACK_POSITIVE("FEEDBACK_POSITIVE"),
    FEEDBACK_POSTPONE("FEEDBACK_POSTPONE"),
    FEEDBACK_DISMISS("FEEDBACK_DISMISS"),
}
