package com.ubb.fmi.orar.domain.analytics.model

/**
 * Events for logging key actions in Firebase
 */
enum class AnalyticsEvent(val id: String) {
    CONFIG_STUDENT("CONFIG_STUDENT"),
    CONFIG_TEACHER("CONFIG_TEACHER"),

    VIEW_TIMETABLE_GROUP("VIEW_TIMETABLE_GROUP"),
    VIEW_TIMETABLE_TEACHER("VIEW_TIMETABLE_TEACHER"),
    VIEW_TIMETABLE_SUBJECT("VIEW_TIMETABLE_SUBJECT"),
    VIEW_TIMETABLE_ROOM("VIEW_TIMETABLE_ROOM"),

    NEWS_ACCESS_STUDENT("NEWS_ACCESS_STUDENT"),
    NEWS_ACCESS_TEACHER("NEWS_ACCESS_TEACHER"),

    ADD_PERSONAL_EVENT("ADD_PERSONAL_EVENT"),

    ADOPT_EVENT("ADOPT_EVENT"),

    FREE_ROOM_SEARCH("FREE_ROOM_SEARCH"),

    FEEDBACK_SHOW("FEEDBACK_SHOW"),
    FEEDBACK_NEGATIVE("FEEDBACK_NEGATIVE"),
    FEEDBACK_NEUTRAL("FEEDBACK_NEUTRAL"),
    FEEDBACK_POSITIVE("FEEDBACK_POSITIVE"),
    FEEDBACK_POSTPONE("FEEDBACK_POSTPONE"),
    FEEDBACK_DISMISS("FEEDBACK_DISMISS"),

    NOTIFICATION_PERMISSION_GRANTED("NOTIFICATION_PERMISSION_GRANTED"),
    NOTIFICATION_PERMISSION_DENIED("NOTIFICATION_PERMISSION_DENIED"),
    NOTIFICATIONS_ENABLED("NOTIFICATIONS_ENABLED"),
    NOTIFICATIONS_DISABLED("NOTIFICATIONS_DISABLED"),
    NOTIFICATION_ADVANCE_CHANGED("NOTIFICATION_ADVANCE_CHANGED"),
    EVENT_NOTIFICATION_ON("EVENT_NOTIFICATION_ON"),
    EVENT_NOTIFICATION_OFF("EVENT_NOTIFICATION_OFF"),
    NOTIFICATION_DISPLAYED("NOTIFICATION_DISPLAYED"),
    NOTIFICATION_OPENED("NOTIFICATION_OPENED"),
    EXACT_ALARM_UNAVAILABLE("EXACT_ALARM_UNAVAILABLE"),
    NOTIFICATIONS_RESTORED_AFTER_BOOT("NOTIFICATIONS_RESTORED_AFTER_BOOT"),

    HIDE_EVENT("HIDE_EVENT"),
    SHOW_EVENT("SHOW_EVENT"),
    DELETE_PERSONAL_EVENT("DELETE_PERSONAL_EVENT"),
    EDIT_MODE_OPENED("EDIT_MODE_OPENED"),
    WEEK_FILTER_CHANGED("WEEK_FILTER_CHANGED"),

    TIMETABLE_LOAD_ERROR("TIMETABLE_LOAD_ERROR"),
    TIMETABLE_RETRY("TIMETABLE_RETRY"),

    THEME_CHANGED("THEME_CHANGED"),
    CONFIG_CHANGED("CONFIG_CHANGED"),
    REPORT_ISSUE_CLICK("REPORT_ISSUE_CLICK"),
    REPOSITORY_CLICK("REPOSITORY_CLICK"),
    LEAVE_FEEDBACK_CLICK("LEAVE_FEEDBACK_CLICK"),
}
