complexity:
  LongMethod:
    threshold: 150
  LongParameterList:
    functionThreshold: 20
    constructorThreshold: 10
    ignoreAnnotatedParameter:
      - 'Composable'
      - 'SerializedName'
  TooManyFunctions:
    ignoreOverridden: true
    ignoreAnnotated:
      - 'Preview'

empty-blocks:
    EmptyFunctionBlock:
      ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'Exception'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'

formatting:
  FinalNewline:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    ignoreEnums: true
    ignoreRanges: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - 'Preview'
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 6
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewToystore'